import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "english": "English",
          "hindi": "हिंदी",
          "nepali": "नेपाली",
          "choose_language": "Choose Language",
          'email_hint': "Enter Your Email",
          'password_hint': "Enter Your Password",
          "fullName_hint": "Enter Your Full Name",
          "username_hint": "Enter Your Username",
          "avatar_hint": "Select Avatar Photo",
          "coverImage_hint": "Select Cover Image",
          "select_photo": "No image selected",
          "select_video": "No Video selected",
          "title_hint": "Enter the Title",
          "description_hint": "Enter the Description of Video",
          "video_hint": "Select Video",
          "thumbnail_hint": "Select Thumbnail Image",
          'internet_exception': "Internet Unavailable\nPlease check your internet connection",
          'retry': "Retry",
          'general_exception': "We're unable to process your request.\nPlease try again",
          "setting_up": "We're setting things up for you. This will only take a moment.",
          "welcome": "Hello and Welcome",
          "login_screen": "Login Screen",
          "register_screen": "Register Screen",
          "profile_screen": "Profile Screen",
          "back_to_login": "Back to Login",
          "back": "Back",
          "home_screen": "Home Screen",
          "video_screen": "Video Screen",
          "user_screen": "User Screen",
          "post_video": "Post Video",
          "forgot_password": "Forgot Password?",
          "reset_password": "Reset Password",
          "watch_history": "Watch History",
          "logout": "Logout",
          "sure_logout": "Are you sure want to Logout?",
          "setting": "Settings",
          "login": "Login",
          "register": "Register",
          "update": "Update",
          "change_password": "Change Password",
          "old_password_hint": "Enter Old Password",
          "new_password_hint": "Enter New Password",
          "invalid_email": "Invalid Email",
          "no_video": "No video found",
          "password_length": "Password must be at least 4 characters",
          "update_account": "Update Account Details",
          "update_avatar": "Update Avatar Image",
          "update_coverimage": "Update Cover Image",
          "update_video": "Update Video",
          "add_comment": "Add a comment",
          "subscribed": "Subscribed",
          "subscribe": "Subscribe",
          "comments": "Comments",
          "get_liked_videos": "Get Liked Videos",
          "liked_videos": "Liked Videos",
          "change_theme": "Change Theme",
          "no_data": "No Data Found",
          "delete_video": "Delete Video",
          "are_you_sure": "Are you sure you want to delete?",
          "subscribers": "Subscribers",
          "settings": "Settings",
          "search": "Search",
          "search_video": "Search Video",
          "error": "Error",
          'edit_comment': "Edit Comment",
          'delete_comment': "Delete Comment",
          'delete': "Delete",
          'update_comment': "Update Comment",
          'cancel': "Cancel",
          'comment_cannot_empty': "Comment cannot be empty",
          'error_init_video': "Error initializing video:",
          'save': "Save",
          "are_you_sure_you_want_to_delete": "Are you sure you want to delete this comment?",
          "desc": "Description:",
          'total_views': "Total Views:",
          'total_subscribers': "Total Subscribers:",
          'uploaded': "Uploaded",
          'success': "Success",
          'password_changed_successfully': "Password Changed Successfully",
          'password_change_failed': "Password Change Failed",
          'password_reset_success': "Password Reset Successfully",
          'login_success': "Login Successfully",
          'failed_to_save_user': "Failed to save user data",
          'login_failed': "Login Failed",
          'invalid_response': "Invalid response",
          'logout_failed': "Logout Failed",
          'logout_success': "Logout Successfully",
          'error_api_call': "Error while api call",
          'register_success': "Registered Successfully",
          'unknown_error': "Unknown error occurred",
          'error_register': "Error while registering",
          'register_failed': "Registration Failed",
          'account_updated': "Account Updated Successfully",
          'avatar_updated': "Avatar Updated Successfully",
          'coverimage_updated': "Coverimage Updated Successfully",
          'video_updated': "Video Updated Successfully",
          'video_deleted': "Video deleted successfully",
          'video_posted': "Video posted successfully",
          'no_watch_history': "No watch history found",
          'chat_screen': "Chat Screen",
          'no_chats': "No Chats Found",
          'chat_created': "Chat Created Successfully",
          'available_users': "Available Users",
        },
        'hi_IN': {
          "english": "अंग्रेज़ी",
          "hindi": "हिंदी",
          "nepali": "नेपाली",
          "choose_language": "भाषा चुनें",
          'email_hint': "अपना ईमेल दर्ज करें",
          'password_hint': "अपना पासवर्ड दर्ज करें",
          "fullName_hint": "अपना पूरा नाम दर्ज करें",
          "username_hint": "अपना उपयोगकर्ता नाम दर्ज करें",
          "avatar_hint": "अवतार फोटो चुनें",
          "coverImage_hint": "कवर इमेज चुनें",
          "select_photo": "कोई फोटो नहीं चुनी गई",
          "select_video": "कोई वीडियो नहीं चुना गया",
          "title_hint": "शीर्षक दर्ज करें",
          "description_hint": "वीडियो का विवरण दर्ज करें",
          "video_hint": "वीडियो चुनें",
          "thumbnail_hint": "थंबनेल इमेज चुनें",
          'internet_exception': "इंटरनेट उपलब्ध नहीं है\nकृपया अपने इंटरनेट कनेक्शन की जांच करें",
          'retry': "पुन: प्रयास करें",
          'general_exception': "हम आपकी अनुरोध प्रक्रिया नहीं कर पा रहे हैं।\nकृपया पुन: प्रयास करें",
          "setting_up": "हम आपके लिए सेटअप कर रहे हैं। इसमें कुछ पल लगेंगे।",
          "welcome": "नमस्ते और स्वागत है",
          "login_screen": "लॉगिन स्क्रीन",
          "register_screen": "रजिस्टर स्क्रीन",
          "profile_screen": "प्रोफ़ाइल स्क्रीन",
          "back_to_login": "लॉगिन पर वापस जाएं",
          "back": "वापस",
          "home_screen": "होम स्क्रीन",
          "video_screen": "वीडियो स्क्रीन",
          "user_screen": "उपयोगकर्ता स्क्रीन",
          "post_video": "वीडियो पोस्ट करें",
          "forgot_password": "पासवर्ड भूल गए?",
          "reset_password": "पासवर्ड रीसेट करें",
          "watch_history": "देखे गए वीडियो",
          "logout": "लॉगआउट",
          "sure_logout": "क्या आप वाकई लॉगआउट करना चाहते हैं?",
          "setting": "सेटिंग्स",
          "login": "लॉगिन",
          "register": "रजिस्टर",
          "update": "अपडेट करें",
          "change_password": "पासवर्ड बदलें",
          "old_password_hint": "पुराना पासवर्ड दर्ज करें",
          "new_password_hint": "नया पासवर्ड दर्ज करें",
          "invalid_email": "अमान्य ईमेल",
          "no_video": "कोई वीडियो नहीं मिला",
          "password_length": "पासवर्ड कम से कम 4 अक्षरों का होना चाहिए",
          "update_account": "खाता विवरण अपडेट करें",
          "update_avatar": "अवतार इमेज अपडेट करें",
          "update_coverimage": "कवर इमेज अपडेट करें",
          "update_video": "वीडियो अपडेट करें",
          "add_comment": "एक टिप्पणी जोड़ें",
          "subscribed": "सदस्यता ली हुई",
          "subscribe": "सदस्यता लें",
          "comments": "टिप्पणियाँ",
          "get_liked_videos": "पसंदीदा वीडियो प्राप्त करें",
          "liked_videos": "पसंदीदा वीडियो",
          "change_theme": "थीम बदलें",
          "no_data": "कोई डेटा नहीं मिला",
          "delete_video": "वीडियो हटाएं",
          "are_you_sure": "क्या आप वाकई हटाना चाहते हैं?",
          "subscribers": "सदस्य",
          "settings": "सेटिंग्स",
          "search": "खोजें",
          "search_video": "वीडियो खोजें",
          "error": "त्रुटि",
          'edit_comment': "टिप्पणी संपादित करें",
          'delete_comment': "टिप्पणी हटाएं",
          'delete': "हटाएं",
          'update_comment': "टिप्पणी अपडेट करें",
          'cancel': "रद्द करें",
          'comment_cannot_empty': "टिप्पणी खाली नहीं हो सकती",
          'error_init_video': "वीडियो प्रारंभ करने में त्रुटि:",
          'save': "सहेजें",
          "are_you_sure_you_want_to_delete": "क्या आप वाकई इस टिप्पणी को हटाना चाहते हैं?",
          "desc": "विवरण:",
          'total_views': "कुल दृश्य:",
          'total_subscribers': "कुल सदस्य:",
          'uploaded': "अपलोड किया गया",
          'success': "सफलता",
          'password_changed_successfully': "पासवर्ड सफलतापूर्वक बदल गया",
          'password_change_failed': "पासवर्ड बदलने में विफल",
          'password_reset_success': "पासवर्ड सफलतापूर्वक रीसेट किया गया",
          'login_success': "सफलतापूर्वक लॉगिन हुआ",
          'failed_to_save_user': "उपयोगकर्ता डेटा सहेजने में विफल",
          'login_failed': "लॉगिन विफल",
          'invalid_response': "अमान्य प्रतिक्रिया",
          'logout_failed': "लॉगआउट विफल",
          'logout_success': "सफलतापूर्वक लॉगआउट हुआ",
          'error_api_call': "एपीआई कॉल करते समय त्रुटि",
          'register_success': "सफलतापूर्वक रजिस्टर हुआ",
          'unknown_error': "अज्ञात त्रुटि हुई",
          'error_register': "रजिस्टर करते समय त्रुटि",
          'register_failed': "रजिस्ट्रेशन विफल",
          'account_updated': "खाता सफलतापूर्वक अपडेट हुआ",
          'avatar_updated': "अवतार सफलतापूर्वक अपडेट हुआ",
          'coverimage_updated': "कवर इमेज सफलतापूर्वक अपडेट हुआ",
          'video_updated': "वीडियो सफलतापूर्वक अपडेट हुआ",
          'video_deleted': "वीडियो सफलतापूर्वक हटाया गया",
          'video_posted': "वीडियो सफलतापूर्वक पोस्ट किया गया",
          'no_watch_history': "कोई देखने का इतिहास नहीं मिला",
        },
        'ne_NP': {
          "english": "अंग्रेजी",
          "hindi": "हिन्दी",
          "nepali": "नेपाली",
          "choose_language": "भाषा छान्नुहोस्",
          'email_hint': "आफ्नो इमेल प्रविष्ट गर्नुहोस्",
          'password_hint': "आफ्नो पासवर्ड प्रविष्ट गर्नुहोस्",
          "fullName_hint": "आफ्नो पूरा नाम प्रविष्ट गर्नुहोस्",
          "username_hint": "आफ्नो प्रयोगकर्ता नाम प्रविष्ट गर्नुहोस्",
          "avatar_hint": "अवतार फोटो छान्नुहोस्",
          "coverImage_hint": "कभर इमेज छान्नुहोस्",
          "select_photo": "कुनै फोटो चयन गरिएको छैन",
          "select_video": "कुनै भिडियो चयन गरिएको छैन",
          "title_hint": "शीर्षक प्रविष्ट गर्नुहोस्",
          "description_hint": "भिडियाको विवरण प्रविष्ट गर्नुहोस्",
          "video_hint": "भिडियो छान्नुहोस्",
          "thumbnail_hint": "थम्बनेल इमेज छान्नुहोस्",
          'internet_exception': "इन्टरनेट उपलब्ध छैन\nकृपया आफ्नो इन्टरनेट जाँच गर्नुहोस्",
          'retry': "पुन: प्रयास गर्नुहोस्",
          'general_exception': "हामी तपाईंको अनुरोध प्रक्रिया गर्न असमर्थ छौं।\nकृपया पुन: प्रयास गर्नुहोस्",
          "setting_up": "हामी तपाईंको लागि सेटअप गर्दैछौं। यसमा केहि समय लाग्नेछ।",
          "welcome": "नमस्ते र स्वागत छ",
          "login_screen": "लगइन स्क्रिन",
          "register_screen": "दर्ता स्क्रिन",
          "profile_screen": "प्रोफाइल स्क्रिन",
          "back_to_login": "लगइनमा फिर्ता जानुहोस्",
          "back": "फिर्ता",
          "home_screen": "होम स्क्रिन",
          "video_screen": "भिडियो स्क्रिन",
          "user_screen": "प्रयोगकर्ता स्क्रिन",
          "post_video": "भिडियो पोस्ट गर्नुहोस्",
          "forgot_password": "पासवर्ड बिर्सनुभयो?",
          "reset_password": "पासवर्ड रिसेट गर्नुहोस्",
          "watch_history": "हेर्ने इतिहास",
          "logout": "लगआउट",
          "sure_logout": "के तपाईं साँच्चै लगआउट गर्न चाहनुहुन्छ?",
          "setting": "सेटिङ्स",
          "login": "लगइन",
          "register": "दर्ता गर्नुहोस्",
          "update": "अपडेट गर्नुहोस्",
          "change_password": "पासवर्ड परिवर्तन गर्नुहोस्",
          "old_password_hint": "पुरानो पासवर्ड प्रविष्ट गर्नुहोस्",
          "new_password_hint": "नयाँ पासवर्ड प्रविष्ट गर्नुहोस्",
          "invalid_email": "अवैध इमेल",
          "no_video": "कुनै भिडियो फेला परेन",
          "password_length": "पासवर्ड कम्तिमा 4 अक्षरको हुनुपर्छ",
          "update_account": "खाता विवरण अपडेट गर्नुहोस्",
          "update_avatar": "अवतार इमेज अपडेट गर्नुहोस्",
          "update_coverimage": "कभर इमेज अपडेट गर्नुहोस्",
          "update_video": "भिडियो अपडेट गर्नुहोस्",
          "add_comment": "एक टिप्पणी थप्नुहोस्",
          "subscribed": "सदस्यता लिएको",
          "subscribe": "सदस्यता लिनुहोस्",
          "comments": "टिप्पणिहरू",
          "get_liked_videos": "मन पराएका भिडियोहरू प्राप्त गर्नुहोस्",
          "liked_videos": "मन पराएका भिडियोहरू",
          "change_theme": "थीम परिवर्तन गर्नुहोस्",
          "no_data": "कुनै डाटा फेला परेन",
          "delete_video": "भिडियो हटाउनुहोस्",
          "are_you_sure": "के तपाईं साँच्चै हटाउन चाहनुहुन्छ?",
          "subscribers": "सदस्यहरू",
          "settings": "सेटिङ्स",
          "search": "खोज्नुहोस्",
          "search_video": "भिडियो खोज्नुहोस्",
          "error": "त्रुटि",
          'edit_comment': "टिप्पणी सम्पादन गर्नुहोस्",
          'delete_comment': "टिप्पणी हटाउनुहोस्",
          'delete': "हटाउनुहोस्",
          'update_comment': "टिप्पणी अपडेट गर्नुहोस्",
          'cancel': "रद्द गर्नुहोस्",
          'comment_cannot_empty': "टिप्पणी खाली हुन सक्दैन",
          'error_init_video': "भिडियो सुरु गर्न त्रुटि:",
          'save': "सेभ गर्नुहोस्",
          "are_you_sure_you_want_to_delete": "के तपाईं साँच्चै यो टिप्पणी हटाउन चाहनुहुन्छ?",
          "desc": "विवरण:",
          'total_views': "कुल दृश्यहरू:",
          'total_subscribers': "कुल सदस्यहरू:",
          'uploaded': "अपलोड गरिएको",
          'success': "सफलता",
          'password_changed_successfully': "पासवर्ड सफलतापूर्वक परिवर्तन भयो",
          'password_change_failed': "पासवर्ड परिवर्तन गर्न असफल",
          'password_reset_success': "पासवर्ड सफलतापूर्वक रिसेट भयो",
          'login_success': "सफलतापूर्वक लगइन भयो",
          'failed_to_save_user': "प्रयोगकर्ता डेटा सेभ गर्न असफल",
          'login_failed': "लगइन असफल",
          'invalid_response': "अवैध प्रतिक्रिया",
          'logout_failed': "लगआउट गर्न असफल",
          'logout_success': "सफलतापूर्वक लगआउट भयो",
          'error_api_call': "एपीआई कल गर्दा त्रुटि",
          'register_success': "सफलतापूर्वक दर्ता भयो",
          'unknown_error': "अज्ञात त्रुटि भएको छ",
          'error_register': "दर्ता गर्दा त्रुटि",
          'register_failed': "दर्ता असफल",
          'account_updated': "खाता सफलतापूर्वक अपडेट भयो",
          'avatar_updated': "अवतार सफलतापूर्वक अपडेट भयो",
          'coverimage_updated': "कभर इमेज सफलतापूर्वक अपडेट भयो",
          'video_updated': "भिडियो सफलतापूर्वक अपडेट भयो",
          'video_deleted': "भिडियो सफलतापूर्वक हटाइयो",
          'video_posted': "भिडियो सफलतापूर्वक पोस्ट भयो",
          'no_watch_history': "हेर्ने इतिहास फेला परेन",
        },
      };
}
